//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.15 at 04:33:01 PM EDT 
//


package com.cvs.vcs.storefeed.fileparsingjJaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "strnbr",
    "statcd",
    "statdsc",
    "streetaddr1",
    "cityname",
    "statecd",
    "zipcd",
    "countycd",
    "countycddsc",
    "opcodsc",
    "bussegment",
    "facilitytypcd",
    "facilitytypdsc",
    "divname",
    "fsareanbr",
    "fsregionnbr",
    "fsdistrictnbr",
    "rxareanbr",
    "rxregionnbr",
    "rxdistrictnbr",
    "latitude",
    "longitude",
    "rxphonenbr",
    "dstrmgrfnme",
    "dstrmgrlnme",
    "dstrmgrphonenbr",
    "dstrmgremail",
    "divcd"
})
@XmlRootElement(name = "STORE")
public class STORE {

    @XmlElement(name = "STR_NBR", required = true)
    protected String strnbr;
    @XmlElement(name = "STAT_CD")
    protected Integer statcd;
    @XmlElement(name = "STAT_DSC")
    protected String statdsc;
    @XmlElement(name = "STREET_ADDR1")
    protected String streetaddr1;
    @XmlElement(name = "CITY_NAME")
    protected String cityname;
    @XmlElement(name = "STATE_CD")
    protected String statecd;
    @XmlElement(name = "ZIP_CD")
    protected String zipcd;
    @XmlElement(name = "COUNTY_CD")
    protected String countycd;
    @XmlElement(name = "COUNTY_CD_DSC")
    protected String countycddsc;
    @XmlElement(name = "OPCO_DSC")
    protected String opcodsc;
    @XmlElement(name = "BUS_SEGMENT")
    protected String bussegment;
    @XmlElement(name = "FACILITY_TYP_CD")
    protected String facilitytypcd;
    @XmlElement(name = "FACILITY_TYP_DSC")
    protected String facilitytypdsc;
    @XmlElement(name = "DIV_NAME")
    protected String divname;
    @XmlElement(name = "FS_AREA_NBR")
    protected String fsareanbr;
    @XmlElement(name = "FS_REGION_NBR")
    protected String fsregionnbr;
    @XmlElement(name = "FS_DISTRICT_NBR")
    protected String fsdistrictnbr;
    @XmlElement(name = "RX_AREA_NBR")
    protected String rxareanbr;
    @XmlElement(name = "RX_REGION_NBR")
    protected String rxregionnbr;
    @XmlElement(name = "RX_DISTRICT_NBR")
    protected String rxdistrictnbr;
    @XmlElement(name = "LATITUDE")
    protected String latitude;
    @XmlElement(name = "LONGITUDE")
    protected String longitude;
    @XmlElement(name = "RX_PHONE_NBR")
    protected String rxphonenbr;
    @XmlElement(name = "DSTR_MGR_FNME")
    protected String dstrmgrfnme;
    @XmlElement(name = "DSTR_MGR_LNME")
    protected String dstrmgrlnme;
    @XmlElement(name = "DSTR_MGR_PHONE_NBR")
    protected String dstrmgrphonenbr;
    @XmlElement(name = "DSTR_MGR_EMAIL")
    protected String dstrmgremail;
    @XmlElement(name = "DIV_CD")
    protected String divcd;

    /**
     * Gets the value of the strnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRNBR() {
        return strnbr;
    }

    /**
     * Sets the value of the strnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRNBR(String value) {
        this.strnbr = value;
    }

    /**
     * Gets the value of the statcd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSTATCD() {
        return statcd;
    }

    /**
     * Sets the value of the statcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSTATCD(Integer value) {
        this.statcd = value;
    }

    /**
     * Gets the value of the statdsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATDSC() {
        return statdsc;
    }

    /**
     * Sets the value of the statdsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATDSC(String value) {
        this.statdsc = value;
    }

    /**
     * Gets the value of the streetaddr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTREETADDR1() {
        return streetaddr1;
    }

    /**
     * Sets the value of the streetaddr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTREETADDR1(String value) {
        this.streetaddr1 = value;
    }

    /**
     * Gets the value of the cityname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITYNAME() {
        return cityname;
    }

    /**
     * Sets the value of the cityname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITYNAME(String value) {
        this.cityname = value;
    }

    /**
     * Gets the value of the statecd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATECD() {
        return statecd;
    }

    /**
     * Sets the value of the statecd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATECD(String value) {
        this.statecd = value;
    }

    /**
     * Gets the value of the zipcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPCD() {
        return zipcd;
    }

    /**
     * Sets the value of the zipcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPCD(String value) {
        this.zipcd = value;
    }

    /**
     * Gets the value of the countycd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTYCD() {
        return countycd;
    }

    /**
     * Sets the value of the countycd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTYCD(String value) {
        this.countycd = value;
    }

    /**
     * Gets the value of the countycddsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTYCDDSC() {
        return countycddsc;
    }

    /**
     * Sets the value of the countycddsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTYCDDSC(String value) {
        this.countycddsc = value;
    }

    /**
     * Gets the value of the opcodsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPCODSC() {
        return opcodsc;
    }

    /**
     * Sets the value of the opcodsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPCODSC(String value) {
        this.opcodsc = value;
    }

    /**
     * Gets the value of the bussegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSSEGMENT() {
        return bussegment;
    }

    /**
     * Sets the value of the bussegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSSEGMENT(String value) {
        this.bussegment = value;
    }

    /**
     * Gets the value of the facilitytypcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACILITYTYPCD() {
        return facilitytypcd;
    }

    /**
     * Sets the value of the facilitytypcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACILITYTYPCD(String value) {
        this.facilitytypcd = value;
    }

    /**
     * Gets the value of the facilitytypdsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACILITYTYPDSC() {
        return facilitytypdsc;
    }

    /**
     * Sets the value of the facilitytypdsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACILITYTYPDSC(String value) {
        this.facilitytypdsc = value;
    }

    /**
     * Gets the value of the divname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIVNAME() {
        return divname;
    }

    /**
     * Sets the value of the divname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIVNAME(String value) {
        this.divname = value;
    }

    /**
     * Gets the value of the fsareanbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSAREANBR() {
        return fsareanbr;
    }

    /**
     * Sets the value of the fsareanbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSAREANBR(String value) {
        this.fsareanbr = value;
    }

    /**
     * Gets the value of the fsregionnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSREGIONNBR() {
        return fsregionnbr;
    }

    /**
     * Sets the value of the fsregionnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSREGIONNBR(String value) {
        this.fsregionnbr = value;
    }

    /**
     * Gets the value of the fsdistrictnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSDISTRICTNBR() {
        return fsdistrictnbr;
    }

    /**
     * Sets the value of the fsdistrictnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSDISTRICTNBR(String value) {
        this.fsdistrictnbr = value;
    }

    /**
     * Gets the value of the rxareanbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRXAREANBR() {
        return rxareanbr;
    }

    /**
     * Sets the value of the rxareanbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRXAREANBR(String value) {
        this.rxareanbr = value;
    }

    /**
     * Gets the value of the rxregionnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRXREGIONNBR() {
        return rxregionnbr;
    }

    /**
     * Sets the value of the rxregionnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRXREGIONNBR(String value) {
        this.rxregionnbr = value;
    }

    /**
     * Gets the value of the rxdistrictnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRXDISTRICTNBR() {
        return rxdistrictnbr;
    }

    /**
     * Sets the value of the rxdistrictnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRXDISTRICTNBR(String value) {
        this.rxdistrictnbr = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLATITUDE() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLATITUDE(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLONGITUDE() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLONGITUDE(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the rxphonenbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRXPHONENBR() {
        return rxphonenbr;
    }

    /**
     * Sets the value of the rxphonenbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRXPHONENBR(String value) {
        this.rxphonenbr = value;
    }

    /**
     * Gets the value of the dstrmgrfnme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSTRMGRFNME() {
        return dstrmgrfnme;
    }

    /**
     * Sets the value of the dstrmgrfnme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSTRMGRFNME(String value) {
        this.dstrmgrfnme = value;
    }

    /**
     * Gets the value of the dstrmgrlnme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSTRMGRLNME() {
        return dstrmgrlnme;
    }

    /**
     * Sets the value of the dstrmgrlnme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSTRMGRLNME(String value) {
        this.dstrmgrlnme = value;
    }

    /**
     * Gets the value of the dstrmgrphonenbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSTRMGRPHONENBR() {
        return dstrmgrphonenbr;
    }

    /**
     * Sets the value of the dstrmgrphonenbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSTRMGRPHONENBR(String value) {
        this.dstrmgrphonenbr = value;
    }

    /**
     * Gets the value of the dstrmgremail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSTRMGREMAIL() {
        return dstrmgremail;
    }

    /**
     * Sets the value of the dstrmgremail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSTRMGREMAIL(String value) {
        this.dstrmgremail = value;
    }

    /**
     * Gets the value of the divcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIVCD() {
        return divcd;
    }

    /**
     * Sets the value of the divcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIVCD(String value) {
        this.divcd = value;
    }

}
