//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.15 at 04:33:01 PM EDT 
//


package com.cvs.PIM.parseXml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cvscaremark.retail.mdm.entities._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OPCODSC_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "OPCO_DSC");
    private final static QName _STATDSC_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "STAT_DSC");
    private final static QName _RXREGIONNBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "RX_REGION_NBR");
    private final static QName _RXPHONENBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "RX_PHONE_NBR");
    private final static QName _ZIPCD_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "ZIP_CD");
    private final static QName _FSREGIONNBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "FS_REGION_NBR");
    private final static QName _FACILITYTYPCD_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "FACILITY_TYP_CD");
    private final static QName _FSAREANBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "FS_AREA_NBR");
    private final static QName _DSTRMGRPHONENBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "DSTR_MGR_PHONE_NBR");
    private final static QName _LATITUDE_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "LATITUDE");
    private final static QName _BUSSEGMENT_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "BUS_SEGMENT");
    private final static QName _RXDISTRICTNBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "RX_DISTRICT_NBR");
    private final static QName _ABBRVNAME_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "ABBRV_NAME");
    private final static QName _CITYNAME_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "CITY_NAME");
    private final static QName _RXAREANBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "RX_AREA_NBR");
    private final static QName _COUNTYCD_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "COUNTY_CD");
    private final static QName _STREETADDR1_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "STREET_ADDR1");
    private final static QName _DIVNAME_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "DIV_NAME");
    private final static QName _DSTRMGRLNME_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "DSTR_MGR_LNME");
    private final static QName _FACILITYTYPDSC_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "FACILITY_TYP_DSC");
    private final static QName _DSTRMGRFNME_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "DSTR_MGR_FNME");
    private final static QName _LONGITUDE_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "LONGITUDE");
    private final static QName _FSDISTRICTNBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "FS_DISTRICT_NBR");
    private final static QName _DSTRMGREMAIL_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "DSTR_MGR_EMAIL");
    private final static QName _DIVCD_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "DIV_CD");
    private final static QName _STATCD_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "STAT_CD");
    private final static QName _STRNBR_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "STR_NBR");
    private final static QName _COUNTYCDDSC_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "COUNTY_CD_DSC");
    private final static QName _STATECD_QNAME = new QName("http://www.cvscaremark.com/retail/mdm/entities/1_0", "STATE_CD");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cvscaremark.retail.mdm.entities._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link STORES }
     * 
     */
    public STORES createSTORES() {
        return new STORES();
    }

    /**
     * Create an instance of {@link STORE }
     * 
     */
    public STORE createSTORE() {
        return new STORE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "OPCO_DSC")
    public JAXBElement<String> createOPCODSC(String value) {
        return new JAXBElement<String>(_OPCODSC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "STAT_DSC")
    public JAXBElement<String> createSTATDSC(String value) {
        return new JAXBElement<String>(_STATDSC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "RX_REGION_NBR")
    public JAXBElement<String> createRXREGIONNBR(String value) {
        return new JAXBElement<String>(_RXREGIONNBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "RX_PHONE_NBR")
    public JAXBElement<String> createRXPHONENBR(String value) {
        return new JAXBElement<String>(_RXPHONENBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "ZIP_CD")
    public JAXBElement<String> createZIPCD(String value) {
        return new JAXBElement<String>(_ZIPCD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "FS_REGION_NBR")
    public JAXBElement<String> createFSREGIONNBR(String value) {
        return new JAXBElement<String>(_FSREGIONNBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "FACILITY_TYP_CD")
    public JAXBElement<String> createFACILITYTYPCD(String value) {
        return new JAXBElement<String>(_FACILITYTYPCD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "FS_AREA_NBR")
    public JAXBElement<String> createFSAREANBR(String value) {
        return new JAXBElement<String>(_FSAREANBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "DSTR_MGR_PHONE_NBR")
    public JAXBElement<String> createDSTRMGRPHONENBR(String value) {
        return new JAXBElement<String>(_DSTRMGRPHONENBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "LATITUDE")
    public JAXBElement<String> createLATITUDE(String value) {
        return new JAXBElement<String>(_LATITUDE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "BUS_SEGMENT")
    public JAXBElement<String> createBUSSEGMENT(String value) {
        return new JAXBElement<String>(_BUSSEGMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "RX_DISTRICT_NBR")
    public JAXBElement<String> createRXDISTRICTNBR(String value) {
        return new JAXBElement<String>(_RXDISTRICTNBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "ABBRV_NAME")
    public JAXBElement<String> createABBRVNAME(String value) {
        return new JAXBElement<String>(_ABBRVNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "CITY_NAME")
    public JAXBElement<String> createCITYNAME(String value) {
        return new JAXBElement<String>(_CITYNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "RX_AREA_NBR")
    public JAXBElement<String> createRXAREANBR(String value) {
        return new JAXBElement<String>(_RXAREANBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "COUNTY_CD")
    public JAXBElement<String> createCOUNTYCD(String value) {
        return new JAXBElement<String>(_COUNTYCD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "STREET_ADDR1")
    public JAXBElement<String> createSTREETADDR1(String value) {
        return new JAXBElement<String>(_STREETADDR1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "DIV_NAME")
    public JAXBElement<String> createDIVNAME(String value) {
        return new JAXBElement<String>(_DIVNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "DSTR_MGR_LNME")
    public JAXBElement<String> createDSTRMGRLNME(String value) {
        return new JAXBElement<String>(_DSTRMGRLNME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "FACILITY_TYP_DSC")
    public JAXBElement<String> createFACILITYTYPDSC(String value) {
        return new JAXBElement<String>(_FACILITYTYPDSC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "DSTR_MGR_FNME")
    public JAXBElement<String> createDSTRMGRFNME(String value) {
        return new JAXBElement<String>(_DSTRMGRFNME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "LONGITUDE")
    public JAXBElement<String> createLONGITUDE(String value) {
        return new JAXBElement<String>(_LONGITUDE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "FS_DISTRICT_NBR")
    public JAXBElement<String> createFSDISTRICTNBR(String value) {
        return new JAXBElement<String>(_FSDISTRICTNBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "DSTR_MGR_EMAIL")
    public JAXBElement<String> createDSTRMGREMAIL(String value) {
        return new JAXBElement<String>(_DSTRMGREMAIL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "DIV_CD")
    public JAXBElement<String> createDIVCD(String value) {
        return new JAXBElement<String>(_DIVCD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "STAT_CD")
    public JAXBElement<Integer> createSTATCD(Integer value) {
        return new JAXBElement<Integer>(_STATCD_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "STR_NBR")
    public JAXBElement<String> createSTRNBR(String value) {
        return new JAXBElement<String>(_STRNBR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "COUNTY_CD_DSC")
    public JAXBElement<String> createCOUNTYCDDSC(String value) {
        return new JAXBElement<String>(_COUNTYCDDSC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cvscaremark.com/retail/mdm/entities/1_0", name = "STATE_CD")
    public JAXBElement<String> createSTATECD(String value) {
        return new JAXBElement<String>(_STATECD_QNAME, String.class, null, value);
    }

}
