//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.15 at 04:33:01 PM EDT 
//


package com.cvs.PIM.parseXml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "store"
})
@XmlRootElement(name = "STORES")
public class STORES {

    @XmlElement(name = "STORE", required = true)
    protected List<STORE> store;

   
    public List<STORE> getSTORE() {
        if (store == null) {
            store = new ArrayList<STORE>();
        }
        return this.store;
    }

}
